export const getExtrasByCategory = (cat, subcat = "") => {
  switch (cat) {
    case "Electronics":
      switch (subcat) {
        case "Mobile Phones":
          return [
            { key: "brand", label: "Brand" },
            { key: "model", label: "Model" },
            { key: "storage", label: "Storage (e.g. 128GB)" },
            { key: "battery", label: "Battery Capacity" },
            { key: "camera", label: "Camera Specs" },
          ];
        case "Laptops & Computers":
          return [
            { key: "brand", label: "Brand" },
            { key: "processor", label: "Processor" },
            { key: "ram", label: "RAM" },
            { key: "storage", label: "Storage" },
            { key: "graphics", label: "Graphics Card" },
          ];
        case "Audio & Headphones":
          return [
            { key: "brand", label: "Brand" },
            { key: "type", label: "Audio Type" },
            { key: "connectivity", label: "Connectivity (Wired/Wireless)" },
          ];
        case "Cameras & Photography":
          return [
            { key: "brand", label: "Brand" },
            { key: "type", label: "Camera Type" },
            { key: "resolution", label: "Resolution" },
            { key: "lens", label: "Lens Included" },
          ];
        case "Wearables":
          return [
            { key: "brand", label: "Brand" },
            { key: "type", label: "Wearable Type" },
            { key: "battery", label: "Battery Life" },
            { key: "compatibility", label: "Compatible Devices" },
          ];
        case "TV & Home Theater":
          return [
            { key: "brand", label: "Brand" },
            { key: "screenSize", label: "Screen Size" },
            { key: "resolution", label: "Resolution" },
            { key: "smartFeatures", label: "Smart Features" },
          ];
        case "Gaming Consoles":
          return [
            { key: "brand", label: "Brand" },
            { key: "model", label: "Model" },
            { key: "storage", label: "Storage" },
            { key: "compatibility", label: "Compatible Games" },
          ];
        case "Accessories":
          return [
            { key: "brand", label: "Brand" },
            { key: "type", label: "Accessory Type" },
            { key: "compatibility", label: "Compatible With" },
          ];
        default:
          return [{ key: "brand", label: "Brand" }];
      }

    case "Fashion":
      switch (subcat) {
        case "Men’s Clothing":
        case "Women’s Clothing":
        case "Kid’s Clothing":
        case "Ethnic & Traditional Wear":
          return [
            { key: "size", label: "Available Sizes" },
            { key: "color", label: "Color Options" },
            { key: "material", label: "Material" },
            { key: "brand", label: "Brand" },
          ];
        case "Footwear":
          return [
            { key: "size", label: "Shoe Sizes" },
            { key: "color", label: "Colors" },
            { key: "brand", label: "Brand" },
            { key: "type", label: "Shoe Type" },
          ];
        case "Bags & Backpacks":
        case "Accessories":
        case "Watches":
          return [
            { key: "brand", label: "Brand" },
            { key: "material", label: "Material" },
            { key: "type", label: "Type / Style" },
          ];
        default:
          return [{ key: "size", label: "Size" }];
      }

    case "Groceries":
      return [
        { key: "expiry", label: "Expiry Date" },
        { key: "weight", label: "Weight/Volume" },
        { key: "organic", label: "Organic (yes/no)" },
        { key: "brand", label: "Brand" },
      ];

    case "Health & Beauty":
      switch (subcat) {
        case "Skincare":
        case "Haircare":
        case "Makeup & Cosmetics":
        case "Vitamins & Supplements":
        case "Fragrances":
        case "Accessories":
          return [
            { key: "ingredients", label: "Key Ingredients" },
            { key: "usage", label: "Usage Instructions" },
            { key: "suitableFor", label: "Suitable For" },
            { key: "brand", label: "Brand" },
            { key: "size", label: "Size / Quantity" },
          ];
        default:
          return [{ key: "brand", label: "Brand" }];
      }

    case "Home & Living":
      switch (subcat) {
        case "Furniture":
        case "Home Decor":
        case "Kitchen & Dining":
        case "Bedding & Bath":
        case "Lighting":
        case "Storage & Organization":
        case "Cleaning Supplies":
        case "Accessories":
          return [
            { key: "dimensions", label: "Dimensions" },
            { key: "material", label: "Material" },
            { key: "brand", label: "Brand" },
            { key: "color", label: "Color" },
          ];
        default:
          return [{ key: "brand", label: "Brand" }];
      }

    case "Sports":
      switch (subcat) {
        case "Outdoor Sports":
        case "Gym & Fitness Equipment":
        case "Cycling & Scooters":
        case "Water Sports":
        case "Sportswear & Footwear":
        case "Accessories":
          return [
            { key: "sportType", label: "Sport Type" },
            { key: "brand", label: "Brand" },
            { key: "material", label: "Material" },
            { key: "size", label: "Size / Dimensions" },
            { key: "weight", label: "Weight" },
          ];
        default:
          return [{ key: "brand", label: "Brand" }];
      }

    default:
      return [{ key: "note", label: "Note" }];
  }
};

export function sampleOrders() {
  return [
    {
      orderId: "o1",
      number: "1001",
      customer: "Alice",
      customerEmail: "alice@example.com",
      total: 45.0,
      status: "Shipped",
      date: "2025-09-18",
      items: [
        {
          productId: "p1",
          name: "Wireless Headphones",
          qty: 2,
          price: 15.0,
          img: "https://placehold.co/100x100/FF0055/ffffff?text=Product1",
        },
        {
          productId: "p3",
          name: "Running Shoes",
          qty: 1,
          price: 25.0,
          img: "https://placehold.co/100x100/22C55E/ffffff?text=Product3",
        },
      ],
    },
    {
      orderId: "o2",
      number: "1002",
      customer: "Bob",
      customerEmail: "bob@example.com",
      total: 6.5,
      status: "Delivered",
      date: "2025-09-19",
      items: [
        {
          productId: "p2",
          name: "Smart Watch",
          qty: 1,
          price: 6.5,
          img: "https://placehold.co/100x100/3B82F6/ffffff?text=Product2",
        },
      ],
    },
    {
      orderId: "o3",
      number: "1003",
      customer: "Charlie",
      customerEmail: "charlie@example.com",
      total: 50.0,
      status: "Processing",
      date: "2025-09-20",
      items: [
        {
          productId: "p1",
          name: "Wireless Headphones",
          qty: 3,
          price: 15.0,
          img: "https://placehold.co/100x100/FF0055/ffffff?text=Product1",
        },
        {
          productId: "p5",
          name: "USB Cable",
          qty: 1,
          price: 4.99,
          img: "https://placehold.co/100x100/FBBF24/ffffff?text=Product5",
        },
      ],
    },
    {
      orderId: "o4",
      number: "1004",
      customer: "Diana",
      customerEmail: "diana@example.com",
      total: 12.0,
      status: "Cancelled",
      date: "2025-09-22",
      items: [
        {
          productId: "p4",
          name: "Laptop Stand",
          qty: 1,
          price: 12.0,
          img: "https://placehold.co/100x100/8B5CF6/ffffff?text=Product4",
        },
      ],
    },
    {
      orderId: "o5",
      number: "1005",
      customer: "Eva",
      customerEmail: "eva@example.com",
      total: 29.99,
      status: "Processing",
      date: "2025-09-28",
      items: [
        {
          productId: "p5",
          name: "USB Cable",
          qty: 6,
          price: 4.99,
          img: "https://placehold.co/100x100/FBBF24/ffffff?text=Product5",
        },
      ],
    },
    {
      orderId: "o6",
      number: "1006",
      customer: "Frank",
      customerEmail: "frank@example.com",
      total: 62.0,
      status: "Shipped",
      date: "2025-10-01",
      items: [
        {
          productId: "p3",
          name: "Running Shoes",
          qty: 2,
          price: 25.0,
          img: "https://placehold.co/100x100/22C55E/ffffff?text=Product3",
        },
        {
          productId: "p4",
          name: "Laptop Stand",
          qty: 1,
          price: 12.0,
          img: "https://placehold.co/100x100/8B5CF6/ffffff?text=Product4",
        },
      ],
    },
  ];
}

export function sampleReturns() {
  return [
    { returnId: "r1", number: "1000", customer: "Eve", reason: "Damaged" },
  ];
}

export const sampleSellers = () => [
  {
    id: 1,
    img: "https://placehold.co/100x100/8B5CF6/ffffff?text=Seller1",
    email: "rahim.khandaker@example.com",
    password: "Rahim@12345",
    confirmPassword: "Rahim@12345",
    fullName: "Mohammad Rahim Khandaker",
    phoneNumber: "+8801712345678",
    NIDNumber: "1990123456789",
    storeName: "Khandaker Electronics",
    productCategory: "Electronics & Accessories",
    businessType: "Sole Proprietorship",
    businessAddress: "House 12, Road 8, Mirpur-2, Dhaka",
    taxId: "TAX-DB-2024-00123",
    tradeLicenseNumber: "TL-2019-04567",
    nidFrontFile: "nid_front_rahim.jpg",
    nidBackFile: "nid_back_rahim.jpg",
    bankName: "BRAC Bank",
    accountNumber: "0123456789012",
    mobileBankName: "bKash",
    mobileBankAccountNumber: "01712345678",
    acceptTerms: true,
  },
  {
    id: 2,
    img: "https://placehold.co/100x100/8B5CF6/ffffff?text=Seller2",
    email: "sadia.ahmed@example.net",
    password: "Sadia!2025",
    confirmPassword: "Sadia!2025",
    fullName: "Sadia Ahmed",
    phoneNumber: "+8801911122233",
    NIDNumber: "1987654321001",
    storeName: "Sadia Fashion House",
    productCategory: "Women Clothing",
    businessType: "Private Limited",
    businessAddress: "Shop 5, Agrabad Commercial Area, Chattogram",
    taxId: "TAX-CTG-2023-0987",
    tradeLicenseNumber: "TL-2021-00999",
    nidFrontFile: null,
    nidBackFile: null,
    bankName: "Dutch-Bangla Bank",
    accountNumber: "9876543210001",
    mobileBankName: "Nagad",
    mobileBankAccountNumber: "01911223344",
    acceptTerms: true,
  },
  {
    id: 3,
    img: "https://placehold.co/100x100/8B5CF6/ffffff?text=Seller3",
    email: "tawhid.dev@example.org",
    password: "TawhidDev#1",
    confirmPassword: "TawhidDev#1",
    fullName: "Tawhid Islam",
    phoneNumber: "+8801819988776",
    NIDNumber: "2000012345678",
    storeName: "Deep Tech Store",
    productCategory: "Computer & Peripherals",
    businessType: "Partnership",
    businessAddress: "Level 3, Tech Park, Uttara, Dhaka",
    taxId: "TAX-DK-2022-4455",
    tradeLicenseNumber: "TL-2020-33421",
    nidFrontFile: "nid_front_tawhid.png",
    nidBackFile: "nid_back_tawhid.png",
    bankName: "City Bank",
    accountNumber: "11002200330044",
    mobileBankName: "Rocket",
    mobileBankAccountNumber: "01899887766",
    acceptTerms: true,
  },
  {
    id: 4,
    img: "https://placehold.co/100x100/8B5CF6/ffffff?text=Seller4",
    email: "farhana.seller@example.com",
    password: "Farhana$789",
    confirmPassword: "Farhana$789",
    fullName: "Farhana Begum",
    phoneNumber: "+8801612349900",
    NIDNumber: "1977009876543",
    storeName: "Begum Home & Living",
    productCategory: "Home Decor",
    businessType: "Sole Proprietorship",
    businessAddress: "House 48, Lane 4, Khulna Sadar, Khulna",
    taxId: "TAX-KH-2021-3001",
    tradeLicenseNumber: "TL-2018-00121",
    nidFrontFile: null,
    nidBackFile: "nid_back_farhana.pdf",
    bankName: "Islami Bank Bangladesh",
    accountNumber: "0044123456789",
    mobileBankName: "bKash",
    mobileBankAccountNumber: "01612349900",
    acceptTerms: true,
  },
  {
    id: 5,
    img: "https://placehold.co/100x100/8B5CF6/ffffff?text=Seller5",
    email: "sourav.imports@example.biz",
    password: "SouravImport#55",
    confirmPassword: "SouravImport#55",
    fullName: "Sourav Kumar",
    phoneNumber: "+8801715566778",
    NIDNumber: "1965432109876",
    storeName: "Sourav Imports",
    productCategory: "Household Appliances",
    businessType: "Limited Company",
    businessAddress: "Office 9B, Motijheel, Dhaka",
    taxId: "TAX-MT-2020-7777",
    tradeLicenseNumber: "TL-2017-55678",
    nidFrontFile: "nid_front_sourav.jpg",
    nidBackFile: null,
    bankName: "Standard Chartered Bank",
    accountNumber: "2200110099887",
    mobileBankName: "Nagad",
    mobileBankAccountNumber: "01755667788",
    acceptTerms: true,
  },
];

export const sampleProducts = () => [
  // ---------------- Electronics (8) ----------------
  {
    id: "e1",
    name: "USB-C Fast Charger",
    oldPrice: 29,
    price: 19,
    discount: 34,
    rating: 4.4,
    isBestSeller: true,
    isHot: false,
    isNew: true,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Electronics",
    subcategory: "Accessories",
    description: "Compact USB-C fast charger with overcurrent protection.",
    stock: 240,
    images: ["https://placehold.co/300x300/0ea5e9/FFFFFF?text=Charger"],
    extras: {
      brand: "ChargePro",
      type: "Charger",
      compatibility: "USB-C Devices",
    },
  },
  {
    id: "e2",
    name: "NoiseCancel Headphones",
    oldPrice: 149,
    price: 119,
    discount: 20,
    rating: 4.6,
    isBestSeller: true,
    isHot: true,
    isNew: false,
    isTrending: true,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Electronics",
    subcategory: "Audio & Headphones",
    description:
      "Over-ear Bluetooth headphones with active noise cancellation.",
    stock: 95,
    images: ["https://placehold.co/300x300/7c3aed/FFFFFF?text=Headphones"],
    extras: { brand: "SoundMax", type: "Over-Ear", connectivity: "Wireless" },
  },
  {
    id: "e3",
    name: "Mirrorless Camera 24MP",
    oldPrice: 899,
    price: 749,
    discount: 17,
    rating: 4.7,
    isBestSeller: false,
    isHot: true,
    isNew: true,
    isTrending: false,
    isLimitedStock: true,
    isExclusive: true,
    category: "Electronics",
    subcategory: "Cameras & Photography",
    description:
      "Compact mirrorless camera with 24MP sensor and standard lens.",
    stock: 18,
    images: ["https://placehold.co/300x300/f97316/FFFFFF?text=Camera"],
    extras: {
      brand: "PhotoPro",
      type: "Mirrorless",
      resolution: "24MP",
      lens: "24-70mm Kit",
    },
  },
  {
    id: "e4",
    name: "Home Gaming Console X",
    oldPrice: 499,
    price: 449,
    discount: 10,
    rating: 4.9,
    isBestSeller: true,
    isHot: true,
    isNew: false,
    isTrending: true,
    isLimitedStock: true,
    isExclusive: false,
    isFlashSale: false,
    category: "Electronics",
    subcategory: "Gaming Consoles",
    description: "Next-gen gaming console with ultra-fast loading and 1TB SSD.",
    stock: 25,
    images: ["https://placehold.co/300x300/0ea5a4/FFFFFF?text=Console"],
    extras: {
      brand: "GameSphere",
      model: "G-X1",
      storage: "1TB",
      compatibility: "PS/Xbox Titles",
    },
  },
  {
    id: "e5",
    name: "ProWork Ultrabook 14",
    oldPrice: 1299,
    price: 1199,
    discount: 8,
    rating: 4.5,
    isBestSeller: true,
    isHot: false,
    isNew: true,
    isTrending: true,
    isLimitedStock: false,
    isExclusive: true,
    category: "Electronics",
    subcategory: "Laptops & Computers",
    description: "14-inch ultrabook with Intel i7, 16GB RAM and 512GB SSD.",
    stock: 40,
    images: ["https://placehold.co/300x300/0284c7/FFFFFF?text=Laptop"],
    extras: {
      brand: "TechPro",
      processor: "Intel i7",
      ram: "16GB",
      storage: "512GB SSD",
      graphics: "Integrated",
    },
  },
  {
    id: "e6",
    name: "NovaPhone Z5",
    oldPrice: 799,
    price: 699,
    discount: 13,
    rating: 4.8,
    isBestSeller: true,
    isHot: true,
    isNew: true,
    isTrending: true,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Electronics",
    subcategory: "Mobile Phones",
    description:
      "Flagship smartphone with 108MP main camera and 4500mAh battery.",
    stock: 85,
    images: ["https://placehold.co/300x300/0f766e/FFFFFF?text=Phone"],
    extras: {
      brand: "NovaTech",
      model: "Z5",
      storage: "256GB",
      battery: "4500mAh",
      camera: "108MP + 12MP",
    },
  },
  {
    id: "e7",
    name: 'Vision UHD Smart TV 55"',
    oldPrice: 899,
    price: 749,
    discount: 17,
    rating: 4.7,
    isBestSeller: false,
    isHot: true,
    isNew: true,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: true,
    category: "Electronics",
    subcategory: "TV & Home Theater",
    description:
      "55-inch 4K UHD smart TV with HDR and multiple streaming apps.",
    stock: 36,
    images: ["https://placehold.co/300x300/7c3aed/FFFFFF?text=Smart+TV"],
    extras: {
      brand: "VisionTech",
      screenSize: "55 inch",
      resolution: "4K UHD",
      smartFeatures: "Netflix, YouTube",
    },
  },
  {
    id: "e8",
    name: "ActiveFit Smart Band",
    oldPrice: 99,
    price: 69,
    discount: 30,
    rating: 4.3,
    isBestSeller: true,
    isHot: true,
    isNew: true,
    isTrending: true,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Electronics",
    subcategory: "Wearables",
    description: "Lightweight fitness band with heart-rate and sleep tracking.",
    stock: 150,
    images: ["https://placehold.co/300x300/06b6d4/FFFFFF?text=Smart+Band"],
    extras: {
      brand: "PulseTrack",
      type: "Fitness Band",
      battery: "7 days",
      compatibility: "iOS & Android",
    },
  },

  // ---------------- Fashion (8) ----------------
  {
    id: "f1",
    name: "Minimal Leather Belt",
    oldPrice: 39,
    price: 29,
    discount: 26,
    rating: 4.2,
    isBestSeller: false,
    isHot: false,
    isNew: true,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Fashion",
    subcategory: "Accessories",
    description: "Genuine leather belt with classic metal buckle.",
    stock: 120,
    images: ["https://placehold.co/300x300/7c2d12/FFFFFF?text=Belt"],
    extras: { brand: "Heritage", material: "Leather", type: "Belt" },
  },
  {
    id: "f2",
    name: "CityLife Backpack",
    oldPrice: 79,
    price: 59,
    discount: 25,
    rating: 4.6,
    isBestSeller: true,
    isHot: true,
    isNew: false,
    isTrending: true,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Fashion",
    subcategory: "Bags & Backpacks",
    description:
      "Water-resistant backpack with laptop compartment and organizer pockets.",
    stock: 90,
    images: ["https://placehold.co/300x300/0ea5a4/FFFFFF?text=Backpack"],
    extras: { brand: "BagMaster", material: "Canvas", type: "Backpack" },
  },
  {
    id: "f3",
    name: "Festive Embroidered Kurta",
    oldPrice: 89,
    price: 69,
    discount: 22,
    rating: 4.5,
    isBestSeller: true,
    isHot: false,
    isNew: true,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: true,
    category: "Fashion",
    subcategory: "Ethnic & Traditional Wear",
    description: "Hand-embroidered kurta made from premium cotton.",
    stock: 50,
    images: ["https://placehold.co/300x300/92400e/FFFFFF?text=Kurta"],
    extras: {
      size: ["M", "L", "XL"],
      color: ["Ivory", "Navy"],
      material: "Cotton",
      brand: "EthnicWear",
    },
  },
  {
    id: "f4",
    name: "TrailRunner Sneakers",
    oldPrice: 99,
    price: 79,
    discount: 20,
    rating: 4.4,
    isBestSeller: true,
    isHot: true,
    isNew: false,
    isTrending: true,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Fashion",
    subcategory: "Footwear",
    description: "Lightweight trail sneakers with durable grip sole.",
    stock: 140,
    images: ["https://placehold.co/300x300/0f766e/FFFFFF?text=Sneakers"],
    extras: {
      size: ["7", "8", "9", "10"],
      color: ["Black", "Gray"],
      brand: "Stride",
      type: "Trail",
    },
  },
  {
    id: "f5",
    name: "Kids Fun Tee",
    oldPrice: 19,
    price: 12,
    discount: 37,
    rating: 4.3,
    isBestSeller: false,
    isHot: false,
    isNew: true,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Fashion",
    subcategory: "Kid’s Clothing",
    description: "Soft cotton tee for kids with playful print.",
    stock: 220,
    images: ["https://placehold.co/300x300/f97316/FFFFFF?text=Kids+Tee"],
    extras: {
      size: ["2", "4", "6", "8"],
      color: ["Red", "Blue"],
      material: "Cotton",
      brand: "TinyTrend",
    },
  },
  {
    id: "f6",
    name: "Men’s Casual Shirt",
    oldPrice: 45,
    price: 35,
    discount: 22,
    rating: 4.4,
    isBestSeller: true,
    isHot: true,
    isNew: false,
    isTrending: true,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Fashion",
    subcategory: "Men’s Clothing",
    description: "Classic casual shirt in breathable fabric for daily wear.",
    stock: 160,
    images: ["https://placehold.co/300x300/7c3aed/FFFFFF?text=Mens+Shirt"],
    extras: {
      size: ["M", "L", "XL"],
      color: ["White", "Blue"],
      material: "Cotton",
      brand: "UrbanWear",
    },
  },
  {
    id: "f7",
    name: "Elegance Analog Watch",
    oldPrice: 199,
    price: 149,
    discount: 25,
    rating: 4.5,
    isBestSeller: true,
    isHot: false,
    isNew: true,
    isTrending: false,
    isLimitedStock: true,
    isExclusive: true,
    category: "Fashion",
    subcategory: "Watches",
    description: "Premium analog watch with leather strap and sapphire glass.",
    stock: 28,
    images: ["https://placehold.co/300x300/0ea5e9/FFFFFF?text=Watch"],
    extras: { brand: "LuxeTime", material: "Stainless Steel", type: "Analog" },
  },
  {
    id: "f8",
    name: "Women’s Summer Dress",
    oldPrice: 69,
    price: 49,
    discount: 29,
    rating: 4.6,
    isBestSeller: true,
    isHot: true,
    isNew: true,
    isTrending: true,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Fashion",
    subcategory: "Women’s Clothing",
    description: "Lightweight summer dress with breathable fabric and print.",
    stock: 110,
    images: ["https://placehold.co/300x300/f43f5e/FFFFFF?text=Dress"],
    extras: {
      size: ["S", "M", "L"],
      color: ["Floral", "Blue"],
      material: "Viscose",
      brand: "Solara",
    },
  },

  // ---------------- Groceries (8) ----------------
  {
    id: "g1",
    name: "Reusable Grocery Bag",
    oldPrice: 4,
    price: 2.5,
    discount: 38,
    rating: 4.1,
    isBestSeller: false,
    isHot: false,
    isNew: true,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Groceries",
    subcategory: "Accessories",
    description: "Eco-friendly reusable bag for shopping and storage.",
    stock: 500,
    images: ["https://placehold.co/300x300/16a34a/FFFFFF?text=Grocery+Bag"],
    extras: { expiry: "N/A", weight: "N/A", organic: "No", brand: "EcoCarry" },
  },
  {
    id: "g2",
    name: "Organic Black Tea 200g",
    oldPrice: 12,
    price: 8.5,
    discount: 29,
    rating: 4.7,
    isBestSeller: true,
    isHot: false,
    isNew: false,
    isTrending: true,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Groceries",
    subcategory: "Beverages",
    description: "Rich flavored organic black tea, perfect for mornings.",
    stock: 320,
    images: ["https://placehold.co/300x300/84cc16/FFFFFF?text=Black+Tea"],
    extras: {
      expiry: "2026-03-01",
      weight: "200g",
      organic: "Yes",
      brand: "TeaHarvest",
    },
  },
  {
    id: "g3",
    name: "Extra Virgin Olive Oil 500ml",
    oldPrice: 15,
    price: 12,
    discount: 20,
    rating: 4.5,
    isBestSeller: true,
    isHot: true,
    isNew: false,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Groceries",
    subcategory: "Cooking Essentials",
    description: "Cold-pressed extra virgin olive oil for everyday cooking.",
    stock: 140,
    images: ["https://placehold.co/300x300/f59e0b/FFFFFF?text=Olive+Oil"],
    extras: {
      expiry: "2026-06-30",
      weight: "500ml",
      organic: "No",
      brand: "PurePress",
    },
  },
  {
    id: "g4",
    name: "Free-Range Eggs (12 pcs)",
    oldPrice: 5.5,
    price: 4.5,
    discount: 18,
    rating: 4.4,
    isBestSeller: false,
    isHot: false,
    isNew: false,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Groceries",
    subcategory: "Dairy & Eggs",
    description: "Farm fresh free-range eggs — 12 pieces per pack.",
    stock: 260,
    images: ["https://placehold.co/300x300/ca8a04/FFFFFF?text=Eggs"],
    extras: {
      expiry: "2025-11-15",
      weight: "12 pcs",
      organic: "No",
      brand: "FarmFresh",
    },
  },
  {
    id: "g5",
    name: "Fresh Bananas (1kg)",
    oldPrice: 2.5,
    price: 1.99,
    discount: 20,
    rating: 4.6,
    isBestSeller: true,
    isHot: true,
    isNew: false,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Groceries",
    subcategory: "Fresh Fruits & Vegetables",
    description: "Sweet and ripe bananas sourced locally.",
    stock: 300,
    images: ["https://placehold.co/300x300/16a34a/FFFFFF?text=Bananas"],
    extras: {
      expiry: "2025-10-20",
      weight: "1kg",
      organic: "No",
      brand: "NatureHarvest",
    },
  },
  {
    id: "g6",
    name: "Mixed Vegetable Frozen Pack 500g",
    oldPrice: 6,
    price: 4.5,
    discount: 25,
    rating: 4.2,
    isBestSeller: false,
    isHot: false,
    isNew: true,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Groceries",
    subcategory: "Frozen Foods",
    description: "Blanched mixed vegetables, frozen to retain freshness.",
    stock: 180,
    images: ["https://placehold.co/300x300/06b6d4/FFFFFF?text=Frozen+Veg"],
    extras: {
      expiry: "2026-01-10",
      weight: "500g",
      organic: "No",
      brand: "FrostFresh",
    },
  },
  {
    id: "g7",
    name: "Fresh Salmon Fillet 500g",
    oldPrice: 12,
    price: 10,
    discount: 17,
    rating: 4.8,
    isBestSeller: true,
    isHot: true,
    isNew: false,
    isTrending: false,
    isLimitedStock: true,
    isExclusive: false,
    isFlashSale: false,
    category: "Groceries",
    subcategory: "Meat & Seafood",
    description: "Fresh Atlantic salmon fillet — sushi-grade quality.",
    stock: 40,
    images: ["https://placehold.co/300x300/0ea5a4/FFFFFF?text=Salmon"],
    extras: {
      expiry: "2025-10-18",
      weight: "500g",
      organic: "No",
      brand: "OceanCatch",
    },
  },
  {
    id: "g8",
    name: "Crunchy Chips Variety Pack",
    oldPrice: 4,
    price: 2.99,
    discount: 25,
    rating: 4.0,
    isBestSeller: false,
    isHot: false,
    isNew: false,
    isTrending: true,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Groceries",
    subcategory: "Packaged & Snacks",
    description: "Assorted flavored chips — family size variety pack.",
    stock: 420,
    images: ["https://placehold.co/300x300/f97316/FFFFFF?text=Chips"],
    extras: {
      expiry: "2026-02-10",
      weight: "400g",
      organic: "No",
      brand: "SnackTime",
    },
  },

  // ---------------- Health & Beauty (6) ----------------
  {
    id: "hb1",
    name: "Beauty Serum 30ml",
    oldPrice: 45,
    price: 34,
    discount: 24,
    rating: 4.6,
    isBestSeller: true,
    isHot: true,
    isNew: true,
    isTrending: true,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Health & Beauty",
    subcategory: "Skincare",
    description: "Hydrating serum with Vitamin C and hyaluronic acid.",
    stock: 120,
    images: ["https://placehold.co/300x300/fb7185/FFFFFF?text=Serum"],
    extras: {
      ingredients: ["Vitamin C", "Hyaluronic Acid"],
      usage: "Apply 2 drops daily",
      suitableFor: "All skin types",
      brand: "GlowSkin",
      size: "30ml",
    },
  },
  {
    id: "hb2",
    name: "Nourish Shampoo 400ml",
    oldPrice: 15,
    price: 11,
    discount: 27,
    rating: 4.3,
    isBestSeller: false,
    isHot: true,
    isNew: false,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Health & Beauty",
    subcategory: "Haircare",
    description: "Sulfate-free shampoo for daily nourishment and shine.",
    stock: 200,
    images: ["https://placehold.co/300x300/06b6d4/FFFFFF?text=Shampoo"],
    extras: {
      ingredients: ["Keratin", "Argan Oil"],
      usage: "Use 2-3 times weekly",
      suitableFor: "Dry/Damaged hair",
      brand: "HairCare+",
      size: "400ml",
    },
  },
  {
    id: "hb3",
    name: "Signature Eau de Parfum 50ml",
    oldPrice: 79,
    price: 59,
    discount: 25,
    rating: 4.7,
    isBestSeller: true,
    isHot: false,
    isNew: true,
    isTrending: true,
    isLimitedStock: false,
    isExclusive: true,
    category: "Health & Beauty",
    subcategory: "Fragrances",
    description: "Long-lasting fragrance with woody and citrus notes.",
    stock: 60,
    images: ["https://placehold.co/300x300/7c3aed/FFFFFF?text=Fragrance"],
    extras: {
      ingredients: ["Top: Bergamot", "Base: Cedarwood"],
      usage: "Spritz on pulse points",
      suitableFor: "Unisex",
      brand: "AromaLux",
      size: "50ml",
    },
  },
  {
    id: "hb4",
    name: "Matte Lipstick Set",
    oldPrice: 29,
    price: 19,
    discount: 34,
    rating: 4.4,
    isBestSeller: true,
    isHot: true,
    isNew: false,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Health & Beauty",
    subcategory: "Makeup & Cosmetics",
    description: "Set of 3 long-wear matte lipsticks with rich pigments.",
    stock: 140,
    images: ["https://placehold.co/300x300/f43f5e/FFFFFF?text=Lipstick+Set"],
    extras: {
      ingredients: ["Vitamin E"],
      usage: "Apply evenly",
      suitableFor: "All",
      brand: "BeautyBox",
      size: "3 x 3.5g",
    },
  },
  {
    id: "hb5",
    name: "Vitamin D3 1000IU (60 tabs)",
    oldPrice: 14,
    price: 9.99,
    discount: 29,
    rating: 4.5,
    isBestSeller: true,
    isHot: false,
    isNew: false,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Health & Beauty",
    subcategory: "Vitamins & Supplements",
    description: "Daily Vitamin D3 supplement to support bone health.",
    stock: 300,
    images: ["https://placehold.co/300x300/15803d/FFFFFF?text=Vitamins"],
    extras: {
      ingredients: ["Vitamin D3"],
      usage: "1 tab daily",
      suitableFor: "Adults",
      brand: "NutriWell",
      size: "60 tabs",
    },
  },
  {
    id: "hb6",
    name: "Makeup Brush Set",
    oldPrice: 39,
    price: 29,
    discount: 26,
    rating: 4.2,
    isBestSeller: false,
    isHot: false,
    isNew: true,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Health & Beauty",
    subcategory: "Accessories",
    description: "7-piece synthetic makeup brush set with travel pouch.",
    stock: 180,
    images: ["https://placehold.co/300x300/f97316/FFFFFF?text=Brush+Set"],
    extras: {
      ingredients: "N/A",
      usage: "For applying cosmetics",
      suitableFor: "All",
      brand: "GlamTools",
      size: "7 pcs",
    },
  },

  // ---------------- Home & Living (8) ----------------
  {
    id: "h1",
    name: "Plush Bed Sheet Set (King)",
    oldPrice: 99,
    price: 79,
    discount: 20,
    rating: 4.6,
    isBestSeller: true,
    isHot: false,
    isNew: false,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Home & Living",
    subcategory: "Bedding & Bath",
    description: "Soft and breathable king-size bed sheet set with 4 pieces.",
    stock: 60,
    images: ["https://placehold.co/300x300/7c3aed/FFFFFF?text=Bed+Sheet"],
    extras: {
      dimensions: "200x220 cm",
      material: "Cotton",
      brand: "HomeComfort",
      color: "Ivory",
    },
  },
  {
    id: "h2",
    name: "Eco Multi-Surface Cleaner 1L",
    oldPrice: 9,
    price: 6.5,
    discount: 28,
    rating: 4.1,
    isBestSeller: false,
    isHot: false,
    isNew: true,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Home & Living",
    subcategory: "Cleaning Supplies",
    description:
      "Biodegradable cleaner safe for kitchen and bathroom surfaces.",
    stock: 320,
    images: ["https://placehold.co/300x300/059669/FFFFFF?text=Cleaner"],
    extras: {
      dimensions: "1L",
      material: "Liquid",
      brand: "CleanGreen",
      color: "Blue",
    },
  },
  {
    id: "h3",
    name: "Scandi Coffee Table",
    oldPrice: 249,
    price: 199,
    discount: 20,
    rating: 4.5,
    isBestSeller: true,
    isHot: false,
    isNew: false,
    isTrending: false,
    isLimitedStock: true,
    isExclusive: true,
    category: "Home & Living",
    subcategory: "Furniture",
    description:
      "Minimal oak coffee table with durable finish and storage shelf.",
    stock: 22,
    images: ["https://placehold.co/300x300/f97316/FFFFFF?text=Coffee+Table"],
    extras: {
      dimensions: "120x60x45 cm",
      material: "Engineered Wood",
      brand: "HomeCraft",
      color: "Oak",
    },
  },
  {
    id: "h4",
    name: "Abstract Wall Art Frame",
    oldPrice: 79,
    price: 59,
    discount: 25,
    rating: 4.3,
    isBestSeller: false,
    isHot: true,
    isNew: true,
    isTrending: true,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Home & Living",
    subcategory: "Home Decor",
    description: "Modern abstract print in a slim black frame — ready to hang.",
    stock: 140,
    images: ["https://placehold.co/300x300/7c3aed/FFFFFF?text=Wall+Art"],
    extras: {
      dimensions: "60x40 cm",
      material: "Canvas & Frame",
      brand: "DecorStudio",
      color: "Multicolor",
    },
  },
  {
    id: "h5",
    name: "12-piece Non-stick Cookware Set",
    oldPrice: 249,
    price: 199,
    discount: 20,
    rating: 4.6,
    isBestSeller: true,
    isHot: true,
    isNew: false,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Home & Living",
    subcategory: "Kitchen & Dining",
    description: "Durable non-stick cookware set suitable for all stovetops.",
    stock: 80,
    images: ["https://placehold.co/300x300/ea580c/FFFFFF?text=Cookware"],
    extras: {
      dimensions: "Set of 12",
      material: "Aluminum Non-stick",
      brand: "CookMaster",
      color: "Black",
    },
  },
  {
    id: "h6",
    name: "Warm Glow Table Lamp",
    oldPrice: 49,
    price: 39,
    discount: 20,
    rating: 4.2,
    isBestSeller: false,
    isHot: false,
    isNew: true,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Home & Living",
    subcategory: "Lighting",
    description: "Desk/table lamp with warm LED light and adjustable arm.",
    stock: 150,
    images: ["https://placehold.co/300x300/06b6d4/FFFFFF?text=Lamp"],
    extras: {
      dimensions: "40x15x15 cm",
      material: "Metal & Glass",
      brand: "LightHouse",
      color: "Brass",
    },
  },
  {
    id: "h7",
    name: "Modular Storage Box Set (3pc)",
    oldPrice: 59,
    price: 44,
    discount: 26,
    rating: 4.1,
    isBestSeller: false,
    isHot: false,
    isNew: true,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Home & Living",
    subcategory: "Storage & Organization",
    description:
      "Stackable storage boxes ideal for closet or pantry organization.",
    stock: 220,
    images: ["https://placehold.co/300x300/16a34a/FFFFFF?text=Storage+Boxes"],
    extras: {
      dimensions: "Varies",
      material: "Plastic",
      brand: "StoreWell",
      color: "Gray",
    },
  },
  {
    id: "h8",
    name: "Kitchen Utensils Set (8pcs)",
    oldPrice: 29,
    price: 19,
    discount: 34,
    rating: 4.0,
    isBestSeller: false,
    isHot: false,
    isNew: true,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Home & Living",
    subcategory: "Accessories",
    description:
      "Durable kitchen utensil set including spatula, ladle and whisk.",
    stock: 300,
    images: ["https://placehold.co/300x300/7c3aed/FFFFFF?text=Utensils"],
    extras: {
      dimensions: "8 pcs",
      material: "Stainless Steel",
      brand: "KitchenPro",
      color: "Silver",
    },
  },

  // ---------------- Sports (6) ----------------
  {
    id: "s1",
    name: "Multi-Sport Water Bottle 1L",
    oldPrice: 19,
    price: 12,
    discount: 37,
    rating: 4.2,
    isBestSeller: true,
    isHot: false,
    isNew: true,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Sports",
    subcategory: "Accessories",
    description: "Insulated water bottle for outdoor and gym use.",
    stock: 400,
    images: ["https://placehold.co/300x300/06b6d4/FFFFFF?text=Bottle"],
    extras: {
      sportType: "General",
      brand: "HydroFit",
      material: "Stainless Steel",
      size: "1L",
      weight: "360g",
    },
  },
  {
    id: "s2",
    name: "City Electric Scooter",
    oldPrice: 499,
    price: 399,
    discount: 20,
    rating: 4.4,
    isBestSeller: true,
    isHot: true,
    isNew: false,
    isTrending: true,
    isLimitedStock: true,
    isExclusive: false,
    isFlashSale: false,
    category: "Sports",
    subcategory: "Cycling & Scooters",
    description: "Foldable electric scooter with 25km range and 250W motor.",
    stock: 45,
    images: ["https://placehold.co/300x300/f97316/FFFFFF?text=E-Scooter"],
    extras: {
      sportType: "Scooting",
      brand: "UrbanRide",
      material: "Aluminum",
      size: "Folded 100x40 cm",
      weight: "12kg",
    },
  },
  {
    id: "s3",
    name: "Home Gym Adjustable Dumbbells (20kg)",
    oldPrice: 199,
    price: 149,
    discount: 25,
    rating: 4.5,
    isBestSeller: true,
    isHot: false,
    isNew: false,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Sports",
    subcategory: "Gym & Fitness Equipment",
    description: "Adjustable dumbbell pair for versatile home workouts.",
    stock: 120,
    images: ["https://placehold.co/300x300/0ea5a4/FFFFFF?text=Dumbbells"],
    extras: {
      sportType: "Gym",
      brand: "FitZone",
      material: "Cast Iron",
      size: "Adjustable to 20kg",
      weight: "20kg",
    },
  },
  {
    id: "s4",
    name: "Hiking Backpack 35L",
    oldPrice: 129,
    price: 99,
    discount: 23,
    rating: 4.6,
    isBestSeller: true,
    isHot: true,
    isNew: false,
    isTrending: true,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Sports",
    subcategory: "Outdoor Sports",
    description:
      "Durable hiking backpack with hydration compatibility and rain cover.",
    stock: 70,
    images: ["https://placehold.co/300x300/7c3aed/FFFFFF?text=Hiking+Pack"],
    extras: {
      sportType: "Hiking",
      brand: "TrailMaster",
      material: "Ripstop Nylon",
      size: "35L",
      weight: "1.1kg",
    },
  },
  {
    id: "s5",
    name: "Compression Running Shorts",
    oldPrice: 39,
    price: 29,
    discount: 26,
    rating: 4.3,
    isBestSeller: false,
    isHot: false,
    isNew: true,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Sports",
    subcategory: "Sportswear & Footwear",
    description: "High-stretch compression shorts for running and training.",
    stock: 160,
    images: ["https://placehold.co/300x300/ef4444/FFFFFF?text=Running+Shorts"],
    extras: {
      sportType: "Running",
      brand: "FlexFit",
      material: "Polyester-Spandex",
      size: ["S", "M", "L"],
      weight: "150g",
    },
  },
  {
    id: "s6",
    name: "Inflatable Kayak Single",
    oldPrice: 699,
    price: 599,
    discount: 14,
    rating: 4.5,
    isBestSeller: false,
    isHot: false,
    isNew: true,
    isTrending: false,
    isLimitedStock: false,
    isExclusive: false,
    isFlashSale: false,
    category: "Sports",
    subcategory: "Water Sports",
    description: "Lightweight inflatable kayak for solo paddlers, quick setup.",
    stock: 22,
    images: ["https://placehold.co/300x300/06b6d4/FFFFFF?text=Kayak"],
    extras: {
      sportType: "Kayaking",
      brand: "AquaRide",
      material: "PVC",
      size: "Single",
      weight: "12kg",
    },
  },
];
